sudo: false
language: python
install: travis_retry pip install tox
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_cleanup: true
  user: pmclanahan
  password:
    secure: Cr3iSfb1OHMY5r5V54I/arCcxK5bml9c08yc45H+R3V5TliENvSl9a6s5v9VOHTkoKLfodMQAhtoaC8u9Jkcy7ABmOXzMfz74L3+Ag+KUEfmiELAmGZA8FCRo4Ow0JAeVpnYmTw4Trn47R0wTtuMPTkDQ8vwwXL5E+Zys1pcC8C2QuZCrcg7w0CRGmqsfOVGANiBvuz7qPcEMWI/jTjXK5CMgjN42k4tCrJB67a4BAy/+zCYg4zj2CYdpIBuNIc4HsVpUnOsb6ipoprKlE1c2MwbrHdnChuVarmLZ7E/NhoVkfxxz1iUQnHq3pZpMFSGVM3hBhSNjyTtoNyvxH7F1WFNZubry9YcbGjS43UTcXNCDlJZhuFY20ssiikFoWbvitASZ5TWeKJMKIN+RJG8VOu5ZOM19BvXfrNwc5HDry6LBhzd2Du/rNchWPGV+Qfo5DS5Uhny7ciwDZzyaRnsq9Zp/FCXxBvIsPghq+bG5FLFCt3avDFmuE0m10OVh1Xh0DPCZ86xAXsr3SATi2WlwPqc2FC76aQ7AZS7kE6c2YRrmeu6BnsI8tkJ9oYenD/bN1fXl7ArUKxvBknl8nOdQsEuYdG6jh6mG20cWknWxbNfYmULcWtylAtVFJcXh+AI1Ke1z7jMPInxtNdVfvPxzwt5BOKSsF6aJZcUjxv+Whc=
  on:
    tags: true
    repo: pmac/django-jinja-markdown
