name: "CI" # Note that this name appears in the README's badge
on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    name: Tests (Python ${{ matrix.python-version }})
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64" # optional x64 (default) or x86.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
      - name: Run tox
        run: tox

  release:
    name: django-jinja-markdown Release
    if: github.event_name == 'release' && github.event.action == 'published'
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10
      - name: Install dependencies for package building only
        run: pip install build
      - name: Build package for upload to PyPI
        run: python -m build .
      - name: Upload the distribution to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
